// <auto-generated />
using System;
using CV_Manager.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CV_Manager.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20230617112532_Schema_1")]
    partial class Schema_1
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("CV_Manager.Data.CV", b =>
                {
                    b.Property<int>("cvId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<DateTime>("birthDay")
                        .HasColumnType("datetime(6)");

                    b.Property<bool>("cs")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("firstName")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("gender")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<bool>("java")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("lastName")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("nationality")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<bool>("python")
                        .HasColumnType("tinyint(1)");

                    b.HasKey("cvId");

                    b.ToTable("CVs");
                });
#pragma warning restore 612, 618
        }
    }
}
